name: Update Config File

on:
  schedule:
    - cron: '0 3 * * *'  # 每天UTC时间3点运行（注意：UTC时间与您本地时间可能有时差）
  workflow_dispatch:  # 允许手动触发

jobs:
  update-config:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Download config file
      run: |
        # 下载文件到临时位置
        curl -s -o /tmp/config.json "https://download2276.mediafire.com/26onngnxmqugHOnOwGu9b3xNLy2RXrLt1RA-EXhpJUFcEAQPO-97KSc6PRG6mjRbPYtjln1z7DPQgMM8MgTgqv0ZBo6WuubU3l5FCGNrEo2sUC4kSz59nvseSOEtMYsaRgVP13v_bGF_Kf8gJ0JoLdVVUl644_xT_2sfc-e71rGcWcM/ff60ynj6z21iqfb/configplus_isadult.json"
        
        # 检查文件是否下载成功
        if [ ! -s /tmp/config.json ]; then
          echo "Error: Downloaded file is empty or failed"
          exit 1
        fi
        
    - name: Check if file has changed
      id: file_check
      run: |
        # 检查文件是否存在且内容是否相同
        if [ -f "config.json" ] && cmp -s "/tmp/config.json" "config.json"; then
          echo "文件无变化，无需提交"
          echo "has_changed=false" >> $GITHUB_OUTPUT
        else
          echo "文件有变化，需要提交"
          echo "has_changed=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Update config file
      if: steps.file_check.outputs.has_changed == 'true'
      run: |
        # 移动文件到仓库根目录
        mv /tmp/config.json config.json
        
    - name: Commit and push changes
      if: steps.file_check.outputs.has_changed == 'true'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add config.json
        git commit -m "chore: 自动更新config.json配置文件 [$(date +'%Y-%m-%d %H:%M')]"
        git push origin main
